version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: faraday
    versions:
    - 1.3.0
    - 1.3.1
  - dependency-name: i18n
    versions:
    - 1.8.7
    - 1.8.8
    - 1.8.9
  - dependency-name: octokit
    versions:
    - 4.20.0
  - dependency-name: ffi
    versions:
    - 1.14.2
